# Generated by Django 2.0.8 on 2018-10-02 20:25

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fishing_equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='smaller_picture',
            field=imagekit.models.fields.ProcessedImageField(upload_to='product_thumbs'),
        ),
    ]
