# Generated by Django 2.0.8 on 2018-10-09 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishing_equipment', '0004_auto_20181005_0919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title']},
        ),
    ]
