# Generated by Django 2.0.8 on 2018-10-09 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishing_equipment', '0005_auto_20181009_0554'),
        ('fishing_net', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='basketitem',
            unique_together={('basket', 'item_sku')},
        ),
    ]
