# Generated by Django 2.0.8 on 2018-10-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing_net', '0002_auto_20181009_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='order_id',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
